# This file is machine-generated - editing it directly is not advised

julia_version = "1.13.1"
manifest_format = "2.1"
project_hash = "c6b3ab5225a515e5a408a1c2e5295d320ca5f45e"

[[deps.Test01]]
path = "."
uuid = "bd288420-5fe6-4eb7-b080-fad3d644b698"
version = "0.0.1-DEV"
